apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 # Number of replicas
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: mkhnoori1/boardgame:latest # Make sure the tag exists, e.g., 'latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Adjust this if your app uses a different port
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Container port that the app is running on
  type: LoadBalancer  # Change to 'NodePort' if running on a local cluster

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boardgame-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: boardgame  # This should match the labels of your service
  namespaceSelector:
    matchNames:
      - default  # Change this to the namespace where your service is running
  endpoints:
  - port: http  # This should match the name of the port in the service
    interval: 30s  # How often Prometheus will scrape metrics
    path: /swagger-stats/metrics  # The metrics path of your app
    targetPort: 8080  # The container port your app is running on

