apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 # Number of replicas
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: mkhnoori1/boardgame:latest # Make sure the tag exists, e.g., 'latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Adjust this if your app uses a different port
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Container port that the app is running on
  type: LoadBalancer  # Change to 'NodePort' if running on a local cluster

